### PR TITLE
Please, accept the .png logo replacement by an .svg logo

### PR DESCRIPTION
**Pull request by dima-brook**

### CODE REVIEW

**Comment by jameswjr** [comment]
Reopening to verify with automated checks.

**Comment by jameswjr** [comment]
Multiple reopens were required to integrate new automated tests.

**Comment by GitHub-BH** [comment]
Please remove .DS_Store in order to be considered for inclusion. Thanks!

**Comment by tezoslibrarian** [comment]
The current logline text is too long, it needs to have a “One-sentence project description”.
You can instead include a one to two paragraph description below the three dashes at the bottom.

**Pull request closed without merging**
