### PR TITLE
added tea

### PR DESCRIPTION
**Pull request by cryi**

### CODE REVIEW

**Comment by tezoslibrarian** [comment]
Many thanks for your submission to the Tezos ecosystem.

Unfortunately, your markdown file failed our automated validation processes.
Please could you edit this line:

```md
twitter: ""
```

and add your Twitter/X link.
Alternatively, delete the whole line if you don't use Twitter.

Apologies - the instructions are not particularly clear so we'll get them updated.

Many thanks,
Tezos Support

**Comment by cryi** [comment]
Fixed @tezoslibrarian

**Comment by cryi** [comment]
We added all TzC related projects

**Comment by tezoslibrarian** [comment]
Many thanks, but please could you submit each project as a separate Github Pull Request.
Individual PRs may only contain one markdown file and one image.

This is necessary because each project is assessed separately.
If one has issues or queries, it won't stop others being accepted.

We will check the documentation to ensure this is clear.

Regards,
Tezos Support

**Comment by cryi** [comment]
Hi @tezoslibrarian, I restored this to add just tea. Other projects are in separate PRs as requested.

#127 starlords
#128 tezbake
#129 tezpay
#130 tezgov

**Review by tezoslibrarian — APPROVED** [review]
Thank you for your submission.
Your project will be added to the ecosystem shortly.

Regards,
Tezos Support

**Pull request merged**
